// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Color int32

const (
	Color_RED   Color = 0
	Color_BLUE  Color = 1
	Color_GREEN Color = 2
)

var Color_name = map[int32]string{
	0: "RED",
	1: "BLUE",
	2: "GREEN",
}

var Color_value = map[string]int32{
	"RED":   0,
	"BLUE":  1,
	"GREEN": 2,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

type HelloRequest struct {
	DisplayName          string        `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Ex                   []*ComplexMsg `protobuf:"bytes,2,rep,name=ex,proto3" json:"ex,omitempty"`
	Jobs                 []string      `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Color                Color         `protobuf:"varint,4,opt,name=color,proto3,enum=helloworld.Color" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *HelloRequest) GetEx() []*ComplexMsg {
	if m != nil {
		return m.Ex
	}
	return nil
}

func (m *HelloRequest) GetJobs() []string {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func (m *HelloRequest) GetColor() Color {
	if m != nil {
		return m.Color
	}
	return Color_RED
}

type ComplexMsg struct {
	DisplayName          string               `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Foo                  *YetAnotherNestedMsg `protobuf:"bytes,2,opt,name=foo,proto3" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ComplexMsg) Reset()         { *m = ComplexMsg{} }
func (m *ComplexMsg) String() string { return proto.CompactTextString(m) }
func (*ComplexMsg) ProtoMessage()    {}
func (*ComplexMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *ComplexMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMsg.Unmarshal(m, b)
}
func (m *ComplexMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMsg.Marshal(b, m, deterministic)
}
func (m *ComplexMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMsg.Merge(m, src)
}
func (m *ComplexMsg) XXX_Size() int {
	return xxx_messageInfo_ComplexMsg.Size(m)
}
func (m *ComplexMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMsg proto.InternalMessageInfo

func (m *ComplexMsg) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ComplexMsg) GetFoo() *YetAnotherNestedMsg {
	if m != nil {
		return m.Foo
	}
	return nil
}

type YetAnotherNestedMsg struct {
	Grades               []int32  `protobuf:"varint,1,rep,packed,name=grades,proto3" json:"grades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *YetAnotherNestedMsg) Reset()         { *m = YetAnotherNestedMsg{} }
func (m *YetAnotherNestedMsg) String() string { return proto.CompactTextString(m) }
func (*YetAnotherNestedMsg) ProtoMessage()    {}
func (*YetAnotherNestedMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *YetAnotherNestedMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_YetAnotherNestedMsg.Unmarshal(m, b)
}
func (m *YetAnotherNestedMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_YetAnotherNestedMsg.Marshal(b, m, deterministic)
}
func (m *YetAnotherNestedMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_YetAnotherNestedMsg.Merge(m, src)
}
func (m *YetAnotherNestedMsg) XXX_Size() int {
	return xxx_messageInfo_YetAnotherNestedMsg.Size(m)
}
func (m *YetAnotherNestedMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_YetAnotherNestedMsg.DiscardUnknown(m)
}

var xxx_messageInfo_YetAnotherNestedMsg proto.InternalMessageInfo

func (m *YetAnotherNestedMsg) GetGrades() []int32 {
	if m != nil {
		return m.Grades
	}
	return nil
}

type HelloReply struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ReplyAt              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=reply_at,json=replyAt,proto3" json:"reply_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{3}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetReplyAt() *timestamp.Timestamp {
	if m != nil {
		return m.ReplyAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("helloworld.Color", Color_name, Color_value)
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*ComplexMsg)(nil), "helloworld.ComplexMsg")
	proto.RegisterType((*YetAnotherNestedMsg)(nil), "helloworld.YetAnotherNestedMsg")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x9b, 0xa4, 0x69, 0xda, 0x57, 0x91, 0x38, 0x42, 0x19, 0x7a, 0x69, 0x08, 0xa8, 0x41,
	0x30, 0xc5, 0x88, 0x57, 0xa1, 0x6a, 0xa8, 0x82, 0xf6, 0x30, 0xea, 0xc1, 0x83, 0xc8, 0x74, 0xf3,
	0x9a, 0x76, 0x99, 0xec, 0x64, 0x67, 0xa6, 0x6c, 0xf3, 0x87, 0xec, 0xff, 0xbb, 0x24, 0x6d, 0x68,
	0x16, 0x7a, 0xd8, 0xdb, 0xbc, 0xf7, 0x7d, 0xf3, 0xe6, 0x37, 0xef, 0x03, 0x7f, 0x8b, 0x42, 0xc8,
	0x3b, 0xa9, 0x44, 0x16, 0x97, 0x4a, 0x1a, 0x49, 0xe0, 0xdc, 0x99, 0xce, 0x72, 0x29, 0x73, 0x81,
	0xf3, 0x46, 0x59, 0xef, 0x37, 0x73, 0xb3, 0x2b, 0x50, 0x1b, 0x5e, 0x94, 0x47, 0x73, 0x78, 0x6f,
	0xc1, 0xb3, 0x6f, 0xb5, 0x9f, 0xe1, 0xed, 0x1e, 0xb5, 0x21, 0x01, 0x8c, 0xb3, 0x9d, 0x2e, 0x05,
	0xaf, 0x56, 0xbc, 0x40, 0x6a, 0x05, 0x56, 0x34, 0x62, 0xdd, 0x16, 0x79, 0x0d, 0x36, 0x1e, 0xa8,
	0x1d, 0x38, 0xd1, 0x38, 0x99, 0xc4, 0x9d, 0xe7, 0xbf, 0xc8, 0xa2, 0x14, 0x78, 0xf8, 0xa9, 0x73,
	0x66, 0xe3, 0x81, 0x10, 0xe8, 0x5f, 0xcb, 0xb5, 0xa6, 0x4e, 0xe0, 0x44, 0x23, 0xd6, 0x9c, 0xc9,
	0x1b, 0x70, 0xaf, 0xa4, 0x90, 0x8a, 0xf6, 0x03, 0x2b, 0x7a, 0x9e, 0xbc, 0x78, 0x7c, 0x5d, 0x48,
	0xc5, 0x8e, 0x7a, 0xc8, 0x01, 0xce, 0xe3, 0x9e, 0x00, 0xf5, 0x1e, 0x9c, 0x8d, 0x94, 0xd4, 0x0e,
	0xac, 0x68, 0x9c, 0xcc, 0xba, 0x63, 0xff, 0xa2, 0x59, 0xdc, 0x48, 0xb3, 0x45, 0xb5, 0x42, 0x6d,
	0x30, 0xab, 0xf1, 0x6a, 0x6f, 0xf8, 0x0e, 0x5e, 0x5e, 0xd0, 0xc8, 0x04, 0x06, 0xb9, 0xe2, 0x19,
	0x6a, 0x6a, 0x05, 0x4e, 0xe4, 0xb2, 0x53, 0x15, 0xfe, 0x03, 0x38, 0x2d, 0xaa, 0x14, 0x15, 0xa1,
	0xe0, 0x15, 0xa8, 0x35, 0xcf, 0x5b, 0x9a, 0xb6, 0x24, 0x1f, 0x61, 0xa8, 0x6a, 0xcb, 0x7f, 0x6e,
	0x4e, 0x38, 0xd3, 0xf8, 0x98, 0x42, 0xdc, 0xa6, 0x10, 0xff, 0x6e, 0x53, 0x60, 0x5e, 0xe3, 0x5d,
	0x98, 0xb7, 0xaf, 0xc0, 0x6d, 0x16, 0x40, 0x3c, 0x70, 0x58, 0xfa, 0xd5, 0xef, 0x91, 0x21, 0xf4,
	0x3f, 0xff, 0xf8, 0x93, 0xfa, 0x16, 0x19, 0x81, 0xbb, 0x64, 0x69, 0xba, 0xf2, 0xed, 0xe4, 0x3b,
	0x78, 0x4b, 0x85, 0x68, 0x50, 0x91, 0x4f, 0x30, 0xfc, 0xc5, 0xab, 0x86, 0x89, 0xd0, 0xee, 0x8f,
	0xbb, 0x79, 0x4e, 0x27, 0x17, 0x94, 0x52, 0x54, 0x61, 0x6f, 0x3d, 0x68, 0x70, 0x3e, 0x3c, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x01, 0xb0, 0x13, 0x85, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}
